#TODO: Force DaemonSet to not run on master.
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: kubevirt-csi-node
  namespace: kubevirt-csi-driver
spec:
  selector:
    matchLabels:
      app: kubevirt-csi-driver
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubevirt-csi-driver
    spec:
      serviceAccount: kubevirt-csi-node-sa
      initContainers:
        - name: prepare-kubevirt-config
          env:
            - name: kubevirt_URL
              valueFrom:
                secretKeyRef:
                  name: kubevirt-credentials
                  key: kubevirt_kubeconfig

      containers:
        - name: csi-driver-registrar
          imagePullPolicy: Always
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.2.0
          args:
            - "--v=5"
            - "--csi-address=/csi/csi.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/kubevirt.io/csi.sock"
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: kubevirt-csi-driver
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          imagePullPolicy: Always
          image: quay.io/kubevirt/csi-driver:latest
          args:
            - "--endpoint=unix:/csi/csi.sock"
            - "--namespace=kubevirt-csi-driver"
            - "--node-name=$(KUBE_NODE_NAME)"
            - "--infra-cluster-kubeconfig=/var/run/secrets/infracluster/kubeconfig"
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: kubevirt_CONFIG
              value: /tmp/config/kubevirt-config.yaml
          volumeMounts:
            - name: kubevirt_credentials
              mountPath: /var/run/secrets/infracluster
            - name: socket-dir
              mountPath: /csi
            - name: config
              mountPath: /tmp/config/
            - name: plugin-dir
              mountPath: /var/lib/kubelet/plugins
              mountPropagation: Bidirectional
            - name: host-dev
              mountPath: /dev
            - name: udev
              mountPath: /run/udev
            - name: mountpoint-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
      volumes:
        - name: kubevirt_credentials
          secret:
            secretName: kubevirt-credentials
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins
            type: Directory
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/kubevirt.io/
            type: DirectoryOrCreate
        - name: host-dev
          hostPath:
            path: /dev
        - name: udev
          hostPath:
            path: /run/udev
        - name: config
          emptyDir: {}
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: DirectoryOrCreate
