kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: kubevirt-csi-plugin
  namespace: kubevirt-csi-driver
spec:
  serviceName: "kubevirt-csi-driver"
  replicas: 1
  selector:
    matchLabels:
      app: kubevirt-csi-driver
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubevirt-csi-driver
    spec:
      serviceAccount: kubevirt-csi-controller-sa
      initContainers:
        # prepare the kubeconfig of the infra cluster and place it under /var/run/infracluster/kubeconfig
        - name: prepare-kubevirt-config
          env:
            - name: kubevirt_URL
              valueFrom:
                secretKeyRef:
                  name: kubevirt-credentials
                  key: kubevirt_url
            - name: kubevirt_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kubevirt-credentials
                  key: kubevirt_username
            - name: kubevirt_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kubevirt-credentials
                  key: kubevirt_password
            - name: kubevirt_CAFILE
              valueFrom:
                secretKeyRef:
                  name: kubevirt-credentials
                  key: kubevirt_cafile
            - name: kubevirt_INSECURE
              valueFrom:
                secretKeyRef:
                  name: kubevirt-credentials
                  key: kubevirt_insecure
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              #!/bin/sh
              cat << EOF > /tmp/config/kubevirt-config.yaml
              kubevirt_url: $kubevirt_URL
              kubevirt_username: $kubevirt_USERNAME
              kubevirt_password: $kubevirt_PASSWORD
              kubevirt_cafile: $kubevirt_CAFILE
              kubevirt_insecure: $kubevirt_INSECURE
              EOF
          volumeMounts:
            - name: config
              mountPath: /tmp/config

      containers:
        - name: csi-external-attacher
          imagePullPolicy: Always
          image: quay.io/k8scsi/csi-attacher:v2.0.0
          args:
            - "--v=4"
            - "--csi-address=/csi/csi.sock"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-external-provisioner
          imagePullPolicy: Always
          image: quay.io/k8scsi/csi-provisioner:v1.5.0
          args:
            - "--v=9"
            - "--csi-address=/csi/csi.sock"
            - "--provisioner=csi.kubevirt.io"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: kubevirt-csi-driver
          imagePullPolicy: Always
          image: quay.io/kubevirt/csi-driver:latest
          args:
            - "--endpoint=unix:/csi/csi.sock"
            - "--namespace=kubevirt-csi-driver"
            - "--infraClusterKubeconfig=/var/run/secrets/"
          ports:
          - containerPort: 9808
            name: healthz
            protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 30
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: kubevirt_CONFIG
              value: /tmp/config/kubevirt-config.yaml
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: config
              mountPath: /tmp/config/
        - name: liveness-probe
          imagePullPolicy: Always
          image: quay.io/k8scsi/livenessprobe:v2.0.0
          args:
           - "--v=5"
           - "--csi-address=/csi/csi.sock"
           - "--health-port=9808"
           - "--probe-timeout=3s"
          volumeMounts:
           - mountPath: /csi
             name: socket-dir
      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: config
          emptyDir: {}
